### ISSUE TITLE
Problems with OSX

### ISSUE THREAD

**Issue by gdgib-roche** [g2forge/forklift#29]
OSX is based on BSD, so things like `tac` aren't available, and `sed` has a different range of expressions.  Some testing would be a good idea.

Changes

* In the github jack, you'll need `echo "com.github" | tr '.' '\n' | awk '{a[i++]=$0} END {for (j=i-1; j>=0;) print a[j--] }' | tr -s '\n' '.' | sed -e "s/.\$//"` to convert warehouse addresses

**Comment by gdgib** [comment]
Fixed by https://github.com/g2forge/forklift/pull/31
